### ISSUE TITLE
Use associative array for issue references in YML

### ISSUE THREAD

**Issue by Blackjacx** [Blackjacx/backlog-notifier#23]
Convert:

```yaml
    - uses: blackjacx/backlog-notifier@1.2.5
      with:
        reference-repo-prefixes: 'BACKLOG, PIT, BUG, FEATURE, UX, QA, BEIWAGEN'
        reference-repo-names: 'backlog, pit-backlog, bugs, feature-requests, ux, qa, beiwagen'
```

to 

```yaml
    - uses: blackjacx/backlog-notifier@1.2.5
      with:
        - references:
             - repo-prefix: BACKLOG
                repo-name: backlog
             - repo-name: PIT
                repo-name: pit-backlog
               ....
```

It will be rendered like this:

```js
{"references"=>[
  {"repo-prefix"=>"BACKLOG", "repo-name"=>backlog}, 
  {"repo-prefix"=>"PIT", "repo-name"=>pit-backlog}
```

This way ot is easier to preserve the `prefix/name` relationship. See https://stackoverflow.com/a/17173956/971329 for further infos.
