### ISSUE TITLE
Provide github token via inputs instead of env. variables

### ISSUE THREAD

**Issue by StefMa** [Blackjacx/backlog-notifier#67]
Right now you have to put the github token via environment variables:
```yml
    - uses: blackjacx/backlog-notifier@1.4.0
      with:
        repo-references: |
          {
            "data": [
              { "repo_id": "BACKLOG", "repo_name": "backlog" },
            ]
          }
      env:
        GITHUB_TOKEN: ${{ secrets.IOKI_BOT_GH_TOKEN }}
```
See 

https://github.com/Blackjacx/backlog-notifier/blob/15990ef9e854dd9004aefa318a00a2fbfd0e3d98/src/index.js#L17

If we move this to an `input`, then we can also provide the default github token.
Not sure if this is useful as probably this github token don't have access to other repos, but maybe you want to inform your issues  within that repo as well? 🤔 

Additionally, I think it looks nicer if this is part of the `with` block and doesn't require an extra `env` statement.
